# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import embedding_pb2 as embedding__pb2


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateEmbedding = channel.unary_unary(
                '/embedding.EmbeddingService/GenerateEmbedding',
                request_serializer=embedding__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.EmbeddingResponse.FromString,
                )
        self.BatchEmbedding = channel.unary_unary(
                '/embedding.EmbeddingService/BatchEmbedding',
                request_serializer=embedding__pb2.BatchEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.BatchEmbeddingResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=embedding__pb2.EmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.EmbeddingResponse.SerializeToString,
            ),
            'BatchEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEmbedding,
                    request_deserializer=embedding__pb2.BatchEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.BatchEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.EmbeddingService/GenerateEmbedding',
            embedding__pb2.EmbeddingRequest.SerializeToString,
            embedding__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedding.EmbeddingService/BatchEmbedding',
            embedding__pb2.BatchEmbeddingRequest.SerializeToString,
            embedding__pb2.BatchEmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
