# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"y\n\x17RouteExplanationRequest\x12\x1e\n\x05route\x18\x01 \x03(\x0b\x32\x0f.llm.POIContext\x12\x16\n\x0euser_interests\x18\x02 \x01(\t\x12\x13\n\x0bsocial_mode\x18\x03 \x01(\t\x12\x11\n\tintensity\x18\x04 \x01(\t\"n\n\nPOIContext\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x11\n\tlocal_tip\x18\x06 \x01(\t\"\x86\x01\n\x18RouteExplanationResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12)\n\x0c\x65xplanations\x18\x02 \x03(\x0b\x32\x13.llm.POIExplanation\x12\r\n\x05notes\x18\x03 \x03(\t\x12\x1f\n\x17\x61tmospheric_description\x18\x04 \x01(\t\":\n\x0ePOIExplanation\x12\x0e\n\x06poi_id\x18\x01 \x01(\x05\x12\x0b\n\x03why\x18\x02 \x01(\t\x12\x0b\n\x03tip\x18\x03 \x01(\t2e\n\nLLMService\x12W\n\x18GenerateRouteExplanation\x12\x1c.llm.RouteExplanationRequest\x1a\x1d.llm.RouteExplanationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROUTEEXPLANATIONREQUEST']._serialized_start=18
  _globals['_ROUTEEXPLANATIONREQUEST']._serialized_end=139
  _globals['_POICONTEXT']._serialized_start=141
  _globals['_POICONTEXT']._serialized_end=251
  _globals['_ROUTEEXPLANATIONRESPONSE']._serialized_start=254
  _globals['_ROUTEEXPLANATIONRESPONSE']._serialized_end=388
  _globals['_POIEXPLANATION']._serialized_start=390
  _globals['_POIEXPLANATION']._serialized_end=448
  _globals['_LLMSERVICE']._serialized_start=450
  _globals['_LLMSERVICE']._serialized_end=551
# @@protoc_insertion_point(module_scope)
