# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import poi_pb2 as poi__pb2


class POIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPOIs = channel.unary_unary(
                '/poi.POIService/GetAllPOIs',
                request_serializer=poi__pb2.GetPOIsRequest.SerializeToString,
                response_deserializer=poi__pb2.GetPOIsResponse.FromString,
                )
        self.GetCategories = channel.unary_unary(
                '/poi.POIService/GetCategories',
                request_serializer=poi__pb2.GetCategoriesRequest.SerializeToString,
                response_deserializer=poi__pb2.GetCategoriesResponse.FromString,
                )
        self.FindCafesNearLocation = channel.unary_unary(
                '/poi.POIService/FindCafesNearLocation',
                request_serializer=poi__pb2.CafeSearchRequest.SerializeToString,
                response_deserializer=poi__pb2.CafeSearchResponse.FromString,
                )


class POIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPOIs(self, request, context):
        """Get all POIs with optional filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Get categories with counts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindCafesNearLocation(self, request, context):
        """Find cafes near location
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_POIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPOIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPOIs,
                    request_deserializer=poi__pb2.GetPOIsRequest.FromString,
                    response_serializer=poi__pb2.GetPOIsResponse.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=poi__pb2.GetCategoriesRequest.FromString,
                    response_serializer=poi__pb2.GetCategoriesResponse.SerializeToString,
            ),
            'FindCafesNearLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.FindCafesNearLocation,
                    request_deserializer=poi__pb2.CafeSearchRequest.FromString,
                    response_serializer=poi__pb2.CafeSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poi.POIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class POIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPOIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/GetAllPOIs',
            poi__pb2.GetPOIsRequest.SerializeToString,
            poi__pb2.GetPOIsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/GetCategories',
            poi__pb2.GetCategoriesRequest.SerializeToString,
            poi__pb2.GetCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindCafesNearLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/FindCafesNearLocation',
            poi__pb2.CafeSearchRequest.SerializeToString,
            poi__pb2.CafeSearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
