# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import poi_pb2 as poi__pb2


class POIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPOIs = channel.unary_unary(
                '/poi.POIService/GetAllPOIs',
                request_serializer=poi__pb2.GetPOIsRequest.SerializeToString,
                response_deserializer=poi__pb2.GetPOIsResponse.FromString,
                )
        self.FindNearbyCoffeeShops = channel.unary_unary(
                '/poi.POIService/FindNearbyCoffeeShops',
                request_serializer=poi__pb2.CoffeeShopRequest.SerializeToString,
                response_deserializer=poi__pb2.CoffeeShopResponse.FromString,
                )
        self.InsertCoffeeBreaks = channel.unary_unary(
                '/poi.POIService/InsertCoffeeBreaks',
                request_serializer=poi__pb2.CoffeeBreakRequest.SerializeToString,
                response_deserializer=poi__pb2.CoffeeBreakResponse.FromString,
                )


class POIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPOIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindNearbyCoffeeShops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertCoffeeBreaks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_POIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPOIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPOIs,
                    request_deserializer=poi__pb2.GetPOIsRequest.FromString,
                    response_serializer=poi__pb2.GetPOIsResponse.SerializeToString,
            ),
            'FindNearbyCoffeeShops': grpc.unary_unary_rpc_method_handler(
                    servicer.FindNearbyCoffeeShops,
                    request_deserializer=poi__pb2.CoffeeShopRequest.FromString,
                    response_serializer=poi__pb2.CoffeeShopResponse.SerializeToString,
            ),
            'InsertCoffeeBreaks': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCoffeeBreaks,
                    request_deserializer=poi__pb2.CoffeeBreakRequest.FromString,
                    response_serializer=poi__pb2.CoffeeBreakResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poi.POIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class POIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPOIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/GetAllPOIs',
            poi__pb2.GetPOIsRequest.SerializeToString,
            poi__pb2.GetPOIsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindNearbyCoffeeShops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/FindNearbyCoffeeShops',
            poi__pb2.CoffeeShopRequest.SerializeToString,
            poi__pb2.CoffeeShopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertCoffeeBreaks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/poi.POIService/InsertCoffeeBreaks',
            poi__pb2.CoffeeBreakRequest.SerializeToString,
            poi__pb2.CoffeeBreakResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
