version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: aitourist-db
    environment:
      POSTGRES_USER: aitourist
      POSTGRES_PASSWORD: dev_password_change_in_prod
      POSTGRES_DB: aitourist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aitourist"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aitourist-network

  redis:
    image: redis:7-alpine
    container_name: aitourist-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - aitourist-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aitourist-api
    environment:
      DATABASE_URL: postgresql://aitourist:dev_password_change_in_prod@db:5432/aitourist_db
      REDIS_URL: redis://redis:6379/0
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      LLM_PROVIDER: ${LLM_PROVIDER:-anthropic}
      LLM_MODEL: ${LLM_MODEL:-claude-sonnet-4-20250514}
      ENVIRONMENT: development
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - backend_cache:/app/.venv
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - aitourist-network
    restart: unless-stopped
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: aitourist-frontend
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - aitourist-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

networks:
  aitourist-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  backend_cache: