# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geocoding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'geocoding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgeocoding.proto\x12\tgeocoding\"/\n\x0eGeocodeRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\"W\n\x0fGeocodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x19\n\x11\x66ormatted_address\x18\x04 \x01(\t\"7\n\x1b\x43oordinateValidationRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"=\n\x1c\x43oordinateValidationResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\xc3\x01\n\x10GeocodingService\x12G\n\x0eGeocodeAddress\x12\x19.geocoding.GeocodeRequest\x1a\x1a.geocoding.GeocodeResponse\x12\x66\n\x13ValidateCoordinates\x12&.geocoding.CoordinateValidationRequest\x1a\'.geocoding.CoordinateValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geocoding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOCODEREQUEST']._serialized_start=30
  _globals['_GEOCODEREQUEST']._serialized_end=77
  _globals['_GEOCODERESPONSE']._serialized_start=79
  _globals['_GEOCODERESPONSE']._serialized_end=166
  _globals['_COORDINATEVALIDATIONREQUEST']._serialized_start=168
  _globals['_COORDINATEVALIDATIONREQUEST']._serialized_end=223
  _globals['_COORDINATEVALIDATIONRESPONSE']._serialized_start=225
  _globals['_COORDINATEVALIDATIONRESPONSE']._serialized_end=286
  _globals['_GEOCODINGSERVICE']._serialized_start=289
  _globals['_GEOCODINGSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
