# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import poi_pb2 as poi__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in poi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class POIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllPOIs = channel.unary_unary(
                '/poi.POIService/GetAllPOIs',
                request_serializer=poi__pb2.GetPOIsRequest.SerializeToString,
                response_deserializer=poi__pb2.GetPOIsResponse.FromString,
                _registered_method=True)
        self.GetCategories = channel.unary_unary(
                '/poi.POIService/GetCategories',
                request_serializer=poi__pb2.GetCategoriesRequest.SerializeToString,
                response_deserializer=poi__pb2.GetCategoriesResponse.FromString,
                _registered_method=True)
        self.FindCafesNearLocation = channel.unary_unary(
                '/poi.POIService/FindCafesNearLocation',
                request_serializer=poi__pb2.CafeSearchRequest.SerializeToString,
                response_deserializer=poi__pb2.CafeSearchResponse.FromString,
                _registered_method=True)


class POIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllPOIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindCafesNearLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_POIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllPOIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPOIs,
                    request_deserializer=poi__pb2.GetPOIsRequest.FromString,
                    response_serializer=poi__pb2.GetPOIsResponse.SerializeToString,
            ),
            'GetCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategories,
                    request_deserializer=poi__pb2.GetCategoriesRequest.FromString,
                    response_serializer=poi__pb2.GetCategoriesResponse.SerializeToString,
            ),
            'FindCafesNearLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.FindCafesNearLocation,
                    request_deserializer=poi__pb2.CafeSearchRequest.FromString,
                    response_serializer=poi__pb2.CafeSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poi.POIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('poi.POIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class POIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllPOIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poi.POIService/GetAllPOIs',
            poi__pb2.GetPOIsRequest.SerializeToString,
            poi__pb2.GetPOIsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poi.POIService/GetCategories',
            poi__pb2.GetCategoriesRequest.SerializeToString,
            poi__pb2.GetCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindCafesNearLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poi.POIService/FindCafesNearLocation',
            poi__pb2.CafeSearchRequest.SerializeToString,
            poi__pb2.CafeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
