# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import route_pb2 as route__pb2


class RoutePlannerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeRoute = channel.unary_unary(
                '/route.RoutePlannerService/OptimizeRoute',
                request_serializer=route__pb2.RouteOptimizationRequest.SerializeToString,
                response_deserializer=route__pb2.RouteOptimizationResponse.FromString,
                )
        self.CalculateRouteGeometry = channel.unary_unary(
                '/route.RoutePlannerService/CalculateRouteGeometry',
                request_serializer=route__pb2.RouteGeometryRequest.SerializeToString,
                response_deserializer=route__pb2.RouteGeometryResponse.FromString,
                )


class RoutePlannerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OptimizeRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRouteGeometry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutePlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OptimizeRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeRoute,
                    request_deserializer=route__pb2.RouteOptimizationRequest.FromString,
                    response_serializer=route__pb2.RouteOptimizationResponse.SerializeToString,
            ),
            'CalculateRouteGeometry': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRouteGeometry,
                    request_deserializer=route__pb2.RouteGeometryRequest.FromString,
                    response_serializer=route__pb2.RouteGeometryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'route.RoutePlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoutePlannerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OptimizeRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/route.RoutePlannerService/OptimizeRoute',
            route__pb2.RouteOptimizationRequest.SerializeToString,
            route__pb2.RouteOptimizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateRouteGeometry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/route.RoutePlannerService/CalculateRouteGeometry',
            route__pb2.RouteGeometryRequest.SerializeToString,
            route__pb2.RouteGeometryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
