apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: aitourist
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-service-sa
  namespace: aitourist
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-role
  namespace: aitourist
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-rolebinding
  namespace: aitourist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway-role
subjects:
- kind: ServiceAccount
  name: gateway-sa
  namespace: aitourist