apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: aitourist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: gateway-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - gateway
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z postgres 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: wait-for-redis
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z redis 6379; do
            echo "Waiting for redis..."
            sleep 2
          done
      - name: wait-for-ml
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z ml-service 50051; do
            echo "Waiting for ml-service..."
            sleep 2
          done
      containers:
      - name: gateway
        image: aitourist/gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aitourist-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: REDIS_PORT
        - name: ML_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: ML_SERVICE_HOST
        - name: ML_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: ML_SERVICE_PORT
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aitourist-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: aitourist-secrets
              key: ANTHROPIC_API_KEY
        - name: TWOGIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: aitourist-secrets
              key: TWOGIS_API_KEY
        - name: LLM_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: LLM_PROVIDER
        - name: LLM_MODEL
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: LLM_MODEL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aitourist-secrets
              key: JWT_SECRET_KEY
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: aitourist-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: aitourist
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: gateway
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: aitourist
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80