apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migration-sql
  namespace: ai-tourist
data:
  migration.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    CREATE TABLE IF NOT EXISTS pois (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        name_en VARCHAR(255),
        lat DOUBLE PRECISION NOT NULL,
        lon DOUBLE PRECISION NOT NULL,
        address VARCHAR(500),
        category VARCHAR(100) NOT NULL,
        tags TEXT[] DEFAULT '{}',
        description TEXT,
        description_en TEXT,
        photo_tip TEXT,
        local_tip TEXT,
        avg_visit_minutes INTEGER DEFAULT 30,
        open_time TIME,
        close_time TIME,
        social_mode VARCHAR(50) DEFAULT 'any',
        intensity_level VARCHAR(50) DEFAULT 'medium',
        rating DOUBLE PRECISION DEFAULT 0.0,
        embedding DOUBLE PRECISION[],
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_pois_category ON pois(category);
    CREATE INDEX IF NOT EXISTS idx_pois_location ON pois USING gist (point(lat, lon));
    CREATE INDEX IF NOT EXISTS idx_pois_rating ON pois(rating DESC);
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: ai-tourist
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h ai-tourist-postgresql -p 5432 -U aitourist; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done;
          echo "PostgreSQL is ready!";
      containers:
      - name: db-migration
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          echo "Running database migration..."
          psql postgresql://aitourist:secure_password_change_in_prod@ai-tourist-postgresql:5432/aitourist_db -f /migration/migration.sql
          echo "✅ Migration complete!"
        volumeMounts:
        - name: migration-sql
          mountPath: /migration
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: migration-sql
        configMap:
          name: db-migration-sql
