# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x05route\"w\n\x18RouteOptimizationRequest\x12\x11\n\tstart_lat\x18\x01 \x01(\x01\x12\x11\n\tstart_lon\x18\x02 \x01(\x01\x12\x1c\n\x04pois\x18\x03 \x03(\x0b\x32\x0e.route.POIInfo\x12\x17\n\x0f\x61vailable_hours\x18\x04 \x01(\x01\"h\n\x07POIInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x19\n\x11\x61vg_visit_minutes\x18\x05 \x01(\x05\x12\x0e\n\x06rating\x18\x06 \x01(\x01\"v\n\x19RouteOptimizationResponse\x12\'\n\x0foptimized_route\x18\x01 \x03(\x0b\x32\x0e.route.POIInfo\x12\x19\n\x11total_distance_km\x18\x02 \x01(\x01\x12\x15\n\rtotal_minutes\x18\x03 \x01(\x05\"b\n\x14RouteGeometryRequest\x12\x11\n\tstart_lat\x18\x01 \x01(\x01\x12\x11\n\tstart_lon\x18\x02 \x01(\x01\x12$\n\twaypoints\x18\x03 \x03(\x0b\x32\x11.route.Coordinate\"&\n\nCoordinate\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"W\n\x15RouteGeometryResponse\x12#\n\x08geometry\x18\x01 \x03(\x0b\x32\x11.route.Coordinate\x12\x19\n\x11total_distance_km\x18\x02 \x01(\x01\x32\xbe\x01\n\x13RoutePlannerService\x12R\n\rOptimizeRoute\x12\x1f.route.RouteOptimizationRequest\x1a .route.RouteOptimizationResponse\x12S\n\x16\x43\x61lculateRouteGeometry\x12\x1b.route.RouteGeometryRequest\x1a\x1c.route.RouteGeometryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROUTEOPTIMIZATIONREQUEST']._serialized_start=22
  _globals['_ROUTEOPTIMIZATIONREQUEST']._serialized_end=141
  _globals['_POIINFO']._serialized_start=143
  _globals['_POIINFO']._serialized_end=247
  _globals['_ROUTEOPTIMIZATIONRESPONSE']._serialized_start=249
  _globals['_ROUTEOPTIMIZATIONRESPONSE']._serialized_end=367
  _globals['_ROUTEGEOMETRYREQUEST']._serialized_start=369
  _globals['_ROUTEGEOMETRYREQUEST']._serialized_end=467
  _globals['_COORDINATE']._serialized_start=469
  _globals['_COORDINATE']._serialized_end=507
  _globals['_ROUTEGEOMETRYRESPONSE']._serialized_start=509
  _globals['_ROUTEGEOMETRYRESPONSE']._serialized_end=596
  _globals['_ROUTEPLANNERSERVICE']._serialized_start=599
  _globals['_ROUTEPLANNERSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
