apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  labels:
    app: {{ .Values.apiGateway.name }}
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
        {{- include "ai-tourist.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.apiGateway.metricsPort }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api-gateway
        image: "{{ .Values.apiGateway.image }}:{{ .Values.apiGateway.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.apiGateway.port }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.apiGateway.metricsPort }}
          protocol: TCP
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: ENVIRONMENT
        - name: EMBEDDING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: EMBEDDING_SERVICE_URL
        - name: RANKING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: RANKING_SERVICE_URL
        - name: ROUTE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: ROUTE_SERVICE_URL
        - name: LLM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: LLM_SERVICE_URL
        - name: GEOCODING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: GEOCODING_SERVICE_URL
        - name: POI_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: POI_SERVICE_URL
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          {{- toYaml .Values.apiGateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  labels:
    app: {{ .Values.apiGateway.name }}
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.apiGateway.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.apiGateway.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: {{ .Values.apiGateway.name }}