apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-tourist-config
  namespace: ai-tourist
data:
  # Database
  DATABASE_URL: "postgresql+asyncpg://gorkycode:gorkycode_pass@postgres:5432/gorkycode"
  POSTGRES_DB: "gorkycode"
  POSTGRES_USER: "gorkycode"
  POSTGRES_PASSWORD: "gorkycode_pass"
  
  # Redis
  REDIS_URL: "redis://redis:6379/0"
  
  # gRPC Service URLs
  EMBEDDING_SERVICE_URL: "embedding-service:50051"
  RANKING_SERVICE_URL: "ranking-service:50052"
  ROUTE_PLANNER_SERVICE_URL: "route-planner-service:50053"
  LLM_SERVICE_URL: "llm-service:50054"
  GEOCODING_SERVICE_URL: "geocoding-service:50055"
  POI_SERVICE_URL: "poi-service:50056"
  
  # ML Models
  EMBEDDING_MODEL: "paraphrase-multilingual-MiniLM-L12-v2"
  
  # LLM Configuration
  LLM_PROVIDER: "anthropic"  # or "openai"
  LLM_MODEL: "claude-sonnet-4-20250514"
  
  # App Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DEFAULT_WALK_SPEED_KMH: "4.5"
  
  # Frontend
  VITE_API_URL: "http://api-gateway:8000"