apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-tourist.fullname" . }}-config
  labels:
    {{- include "ai-tourist.labels" . | nindent 4 }}
data:
  # Database
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  
  # gRPC Service URLs
  EMBEDDING_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-embedding-service:{{ .Values.embeddingService.service.port }}"
  RANKING_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-ranking-service:{{ .Values.rankingService.service.port }}"
  ROUTE_PLANNER_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-route-planner-service:{{ .Values.routePlannerService.service.port }}"
  ROUTE_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-route-planner-service:{{ .Values.routePlannerService.service.port }}"
  LLM_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-llm-service:{{ .Values.llmService.service.port }}"
  GEOCODING_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-geocoding-service:{{ .Values.geocodingService.service.port }}"
  POI_SERVICE_URL: "{{ include "ai-tourist.fullname" . }}-poi-service:{{ .Values.poiService.service.port }}"
  
  # ML Models
  EMBEDDING_MODEL: {{ .Values.embeddingService.model | quote }}
  
  # LLM Configuration
  LLM_PROVIDER: {{ .Values.llm.provider | quote }}
  LLM_MODEL: {{ .Values.llm.model | quote }}
  
  # App Configuration
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  LOG_LEVEL: "INFO"
  DEFAULT_WALK_SPEED_KMH: "4.5"
  WALK_SPEED_KMH: "4.0"
  
  # Ports
  GRPC_PORT: "50051"
  
  # Frontend
  VITE_API_URL: "http://{{ include "ai-tourist.fullname" . }}-api-gateway:8000"
