apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-tourist.fullname" . }}-config
  labels:
    {{- include "ai-tourist.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgresql.username }}:$(DB_PASSWORD)@{{ include "ai-tourist.fullname" . }}-postgresql:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
  REDIS_URL: "redis://{{ include "ai-tourist.fullname" . }}-redis:{{ .Values.redis.port }}/0"
  
  LLM_PROVIDER: {{ .Values.llm.provider | quote }}
  LLM_MODEL: {{ .Values.llm.model | quote }}
  
  EMBEDDING_MODEL: {{ .Values.embeddingService.model | quote }}
  
  EMBEDDING_SERVICE_URL: "{{ .Values.embeddingService.name }}:{{ .Values.embeddingService.port }}"
  RANKING_SERVICE_URL: "{{ .Values.rankingService.name }}:{{ .Values.rankingService.port }}"
  ROUTE_SERVICE_URL: "{{ .Values.routePlannerService.name }}:{{ .Values.routePlannerService.port }}"
  LLM_SERVICE_URL: "{{ .Values.llmService.name }}:{{ .Values.llmService.port }}"
  GEOCODING_SERVICE_URL: "{{ .Values.geocodingService.name }}:{{ .Values.geocodingService.port }}"
  POI_SERVICE_URL: "{{ .Values.poiService.name }}:{{ .Values.poiService.port }}"