apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-tourist.fullname" . }}-embedding-service
  labels:
    app: {{ .Values.embeddingService.name }}
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.embeddingService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.embeddingService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.embeddingService.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      containers:
      - name: embedding-service
        image: "{{ .Values.embeddingService.image }}:{{ .Values.embeddingService.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: {{ .Values.embeddingService.service.port }}
        - name: metrics
          containerPort: 9091
        envFrom:
        - configMapRef:
            name: {{ include "ai-tourist.fullname" . }}-config
        - secretRef:
            name: {{ include "ai-tourist.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.embeddingService.resources | nindent 12 }}
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 10
          periodSeconds: 5
---
