{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-tourist.fullname" . }}-frontend
  labels:
    {{- include "ai-tourist.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-tourist.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
