apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-tourist.fullname" . }}-frontend
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: API_UPSTREAM
          value: "http://{{ include "ai-tourist.fullname" . }}-api-gateway:8000"
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.port }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5