apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ai-tourist.fullname" . }}-poi-loader
  labels:
    {{- include "ai-tourist.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-loader
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "ai-tourist.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: data-loader
    spec:
      restartPolicy: OnFailure
      containers:
      - name: poi-loader
        image: "{{ .Values.poiService.image.repository }}:{{ .Values.poiService.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.poiService.image.pullPolicy }}
        command:
          - python
          - /app/scripts/load_pois.py
        env:
          - name: DATABASE_URL
            value: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.secrets.dbPassword }}@{{ include "ai-tourist.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
          - name: EMBEDDING_MODEL
            value: {{ .Values.ml.embeddingModel | quote }}
          - name: ANTHROPIC_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "ai-tourist.fullname" . }}-secrets
                key: ANTHROPIC_API_KEY
                optional: true
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "ai-tourist.fullname" . }}-secrets
                key: OPENAI_API_KEY
                optional: true
        volumeMounts:
          - name: poi-data
            mountPath: /app/data
            readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
        - name: poi-data
          configMap:
            name: {{ include "ai-tourist.fullname" . }}-poi-data