{{- if .Values.llmService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-tourist.fullname" . }}-llm-service
  labels:
    {{- include "ai-tourist.labels" . | nindent 4 }}
    app.kubernetes.io/component: llm-service
spec:
  type: {{ .Values.llmService.service.type }}
  ports:
    - port: {{ .Values.llmService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-tourist.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: llm-service
{{- end }}
