apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-tourist.fullname" . }}-poi-service
  labels:
    app: {{ .Values.poiService.name }}
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.poiService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.poiService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.poiService.name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.poiService.metricsPort }}"
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:16-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ include "ai-tourist.fullname" . }}-postgresql -p 5432 -U {{ .Values.postgresql.auth.username }}; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done;
          echo "PostgreSQL is ready!";
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-secrets
              key: DB_PASSWORD
      containers:
      - name: poi-service
        image: "{{ .Values.poiService.image.repository }}:{{ .Values.poiService.image.tag }}"
        imagePullPolicy: {{ .Values.poiService.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.poiService.service.port }}
        - name: metrics
          containerPort: {{ .Values.poiService.metricsPort }}
        env:
        - name: GRPC_PORT
          value: "{{ .Values.poiService.service.port }}"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-secrets
              key: DATABASE_URL
        - name: TWOGIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-secrets
              key: TWOGIS_API_KEY
              optional: true
        - name: EMBEDDING_MODEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: EMBEDDING_MODEL
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ include "ai-tourist.fullname" . }}-config
              key: ENVIRONMENT
        resources:
          {{- toYaml .Values.poiService.resources | nindent 12 }}
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 10
          periodSeconds: 5
