apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-tourist.fullname" . }}-ranking-service
  labels:
    app: ranking-service
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rankingService.replicaCount }}
  selector:
    matchLabels:
      app: ranking-service
  template:
    metadata:
      labels:
        app: ranking-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9092"
    spec:
      containers:
      - name: ranking-service
        image: "{{ .Values.rankingService.image.repository }}:{{ .Values.rankingService.image.tag }}"
        imagePullPolicy: {{ .Values.rankingService.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.rankingService.service.port }}
        - name: metrics
          containerPort: 9092
        envFrom:
        - configMapRef:
            name: {{ include "ai-tourist.fullname" . }}-config
        - secretRef:
            name: {{ include "ai-tourist.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.rankingService.resources | nindent 12 }}
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 10
          periodSeconds: 5
