apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-tourist.fullname" . }}-redis-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-tourist.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    {{- include "ai-tourist.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.port }}
          name: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          {{- toYaml .Values.redis.resources | nindent 12 }}
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: {{ include "ai-tourist.fullname" . }}-redis-pvc