# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import geocoding_pb2 as geocoding__pb2


class GeocodingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeocodeAddress = channel.unary_unary(
                '/geocoding.GeocodingService/GeocodeAddress',
                request_serializer=geocoding__pb2.GeocodeRequest.SerializeToString,
                response_deserializer=geocoding__pb2.GeocodeResponse.FromString,
                )
        self.ValidateCoordinates = channel.unary_unary(
                '/geocoding.GeocodingService/ValidateCoordinates',
                request_serializer=geocoding__pb2.CoordinateValidationRequest.SerializeToString,
                response_deserializer=geocoding__pb2.CoordinateValidationResponse.FromString,
                )


class GeocodingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeocodeAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCoordinates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeocodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeocodeAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GeocodeAddress,
                    request_deserializer=geocoding__pb2.GeocodeRequest.FromString,
                    response_serializer=geocoding__pb2.GeocodeResponse.SerializeToString,
            ),
            'ValidateCoordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCoordinates,
                    request_deserializer=geocoding__pb2.CoordinateValidationRequest.FromString,
                    response_serializer=geocoding__pb2.CoordinateValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geocoding.GeocodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeocodingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeocodeAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocoding.GeocodingService/GeocodeAddress',
            geocoding__pb2.GeocodeRequest.SerializeToString,
            geocoding__pb2.GeocodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geocoding.GeocodingService/ValidateCoordinates',
            geocoding__pb2.CoordinateValidationRequest.SerializeToString,
            geocoding__pb2.CoordinateValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
