# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateRouteExplanation = channel.unary_unary(
                '/llm.LLMService/GenerateRouteExplanation',
                request_serializer=llm__pb2.RouteExplanationRequest.SerializeToString,
                response_deserializer=llm__pb2.RouteExplanationResponse.FromString,
                _registered_method=True)
        self.GenerateRouteExplanationAsync = channel.unary_unary(
                '/llm.LLMService/GenerateRouteExplanationAsync',
                request_serializer=llm__pb2.RouteExplanationRequest.SerializeToString,
                response_deserializer=llm__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/llm.LLMService/GetTaskStatus',
                request_serializer=llm__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=llm__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/llm.LLMService/HealthCheck',
                request_serializer=llm__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=llm__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateRouteExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRouteExplanationAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateRouteExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRouteExplanation,
                    request_deserializer=llm__pb2.RouteExplanationRequest.FromString,
                    response_serializer=llm__pb2.RouteExplanationResponse.SerializeToString,
            ),
            'GenerateRouteExplanationAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRouteExplanationAsync,
                    request_deserializer=llm__pb2.RouteExplanationRequest.FromString,
                    response_serializer=llm__pb2.TaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=llm__pb2.TaskStatusRequest.FromString,
                    response_serializer=llm__pb2.TaskStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=llm__pb2.HealthCheckRequest.FromString,
                    response_serializer=llm__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llm.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llm.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateRouteExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GenerateRouteExplanation',
            llm__pb2.RouteExplanationRequest.SerializeToString,
            llm__pb2.RouteExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRouteExplanationAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GenerateRouteExplanationAsync',
            llm__pb2.RouteExplanationRequest.SerializeToString,
            llm__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/GetTaskStatus',
            llm__pb2.TaskStatusRequest.SerializeToString,
            llm__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llm.LLMService/HealthCheck',
            llm__pb2.HealthCheckRequest.SerializeToString,
            llm__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
