# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"q\n\x17RouteExplanationRequest\x12\x16\n\x04pois\x18\x01 \x03(\x0b\x32\x08.llm.POI\x12\x16\n\x0euser_interests\x18\x02 \x01(\t\x12\x13\n\x0bsocial_mode\x18\x03 \x01(\t\x12\x11\n\tintensity\x18\x04 \x01(\t\"w\n\x03POI\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x11\n\tlocal_tip\x18\x06 \x01(\t\x12\x0e\n\x06rating\x18\x07 \x01(\x02\"\x97\x01\n\x18RouteExplanationResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12&\n\x0c\x65xplanations\x18\x02 \x03(\x0b\x32\x10.llm.Explanation\x12\r\n\x05notes\x18\x03 \x03(\t\x12\x1f\n\x17\x61tmospheric_description\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x02\"7\n\x0b\x45xplanation\x12\x0e\n\x06poi_id\x18\x01 \x01(\x05\x12\x0b\n\x03why\x18\x02 \x01(\t\x12\x0b\n\x03tip\x18\x03 \x01(\t\"/\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"b\n\x12TaskStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12-\n\x06result\x18\x02 \x01(\x0b\x32\x1d.llm.RouteExplanationResponse\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"]\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tive_tasks\x18\x04 \x01(\x05\x32\xbb\x02\n\nLLMService\x12W\n\x18GenerateRouteExplanation\x12\x1c.llm.RouteExplanationRequest\x1a\x1d.llm.RouteExplanationResponse\x12P\n\x1dGenerateRouteExplanationAsync\x12\x1c.llm.RouteExplanationRequest\x1a\x11.llm.TaskResponse\x12@\n\rGetTaskStatus\x12\x16.llm.TaskStatusRequest\x1a\x17.llm.TaskStatusResponse\x12@\n\x0bHealthCheck\x12\x17.llm.HealthCheckRequest\x1a\x18.llm.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEEXPLANATIONREQUEST']._serialized_start=18
  _globals['_ROUTEEXPLANATIONREQUEST']._serialized_end=131
  _globals['_POI']._serialized_start=133
  _globals['_POI']._serialized_end=252
  _globals['_ROUTEEXPLANATIONRESPONSE']._serialized_start=255
  _globals['_ROUTEEXPLANATIONRESPONSE']._serialized_end=406
  _globals['_EXPLANATION']._serialized_start=408
  _globals['_EXPLANATION']._serialized_end=463
  _globals['_TASKRESPONSE']._serialized_start=465
  _globals['_TASKRESPONSE']._serialized_end=512
  _globals['_TASKSTATUSREQUEST']._serialized_start=514
  _globals['_TASKSTATUSREQUEST']._serialized_end=550
  _globals['_TASKSTATUSRESPONSE']._serialized_start=552
  _globals['_TASKSTATUSRESPONSE']._serialized_end=650
  _globals['_HEALTHCHECKREQUEST']._serialized_start=652
  _globals['_HEALTHCHECKREQUEST']._serialized_end=672
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=674
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=767
  _globals['_LLMSERVICE']._serialized_start=770
  _globals['_LLMSERVICE']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
