# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x02ml\"3\n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tuse_cache\x18\x02 \x01(\x08\"a\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x12\n\nfrom_cache\x18\x02 \x01(\x08\x12\x11\n\tdimension\x18\x03 \x01(\x05\x12\x12\n\nlatency_ms\x18\x04 \x01(\x02\"9\n\x15\x45mbeddingBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\tuse_cache\x18\x02 \x01(\x08\"X\n\x16\x45mbeddingBatchResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.ml.EmbeddingResult\x12\x18\n\x10total_latency_ms\x18\x02 \x01(\x02\"8\n\x0f\x45mbeddingResult\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x12\n\nfrom_cache\x18\x02 \x01(\x08\"5\n\x11SimilarityRequest\x12\x0f\n\x07vector1\x18\x01 \x03(\x02\x12\x0f\n\x07vector2\x18\x02 \x03(\x02\"(\n\x12SimilarityResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\"\x14\n\x12HealthCheckRequest\"g\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x17\n\x0fmodel_dimension\x18\x03 \x01(\x05\x12\x12\n\ncache_size\x18\x04 \x01(\x03\x32\xa8\x02\n\x10\x45mbeddingService\x12@\n\x11GenerateEmbedding\x12\x14.ml.EmbeddingRequest\x1a\x15.ml.EmbeddingResponse\x12O\n\x16GenerateEmbeddingBatch\x12\x19.ml.EmbeddingBatchRequest\x1a\x1a.ml.EmbeddingBatchResponse\x12\x41\n\x10\x43osineSimilarity\x12\x15.ml.SimilarityRequest\x1a\x16.ml.SimilarityResponse\x12>\n\x0bHealthCheck\x12\x16.ml.HealthCheckRequest\x1a\x17.ml.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=16
  _globals['_EMBEDDINGREQUEST']._serialized_end=67
  _globals['_EMBEDDINGRESPONSE']._serialized_start=69
  _globals['_EMBEDDINGRESPONSE']._serialized_end=166
  _globals['_EMBEDDINGBATCHREQUEST']._serialized_start=168
  _globals['_EMBEDDINGBATCHREQUEST']._serialized_end=225
  _globals['_EMBEDDINGBATCHRESPONSE']._serialized_start=227
  _globals['_EMBEDDINGBATCHRESPONSE']._serialized_end=315
  _globals['_EMBEDDINGRESULT']._serialized_start=317
  _globals['_EMBEDDINGRESULT']._serialized_end=373
  _globals['_SIMILARITYREQUEST']._serialized_start=375
  _globals['_SIMILARITYREQUEST']._serialized_end=428
  _globals['_SIMILARITYRESPONSE']._serialized_start=430
  _globals['_SIMILARITYRESPONSE']._serialized_end=470
  _globals['_HEALTHCHECKREQUEST']._serialized_start=472
  _globals['_HEALTHCHECKREQUEST']._serialized_end=492
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=494
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=597
  _globals['_EMBEDDINGSERVICE']._serialized_start=600
  _globals['_EMBEDDINGSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
