# Global settings
global:
  environment: production

# Secrets (override with .env.yaml)
secrets:
  dbPassword: "change_in_production"
  openaiApiKey: ""
  anthropicApiKey: ""
  twogisApiKey: ""
  jwtSecret: "generate_random_secret"
  encryptionKey: "generate_random_key"

# LLM Configuration
llm:
  provider: "anthropic"
  model: "claude-sonnet-4-20250514"

# Frontend
frontend:
  name: "frontend"
  replicas: 2
  image:
    repository: "ai-tourist-frontend"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# API Gateway
apiGateway:
  name: "api-gateway"
  replicas: 2
  image:
    repository: "ai-tourist-api-gateway"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Embedding Service
embeddingService:
  name: "embedding-service"
  replicas: 2
  image:
    repository: "ai-tourist-embedding-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50051
  metricsPort: 9090
  batchSize: 32
  model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

# Ranking Service
rankingService:
  name: "ranking-service"
  replicas: 2
  image:
    repository: "ai-tourist-ranking-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50052
  metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Route Planner Service
routePlannerService:
  name: "route-planner-service"
  replicas: 2
  image:
    repository: "ai-tourist-route-planner-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50053
  metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# LLM Service
llmService:
  name: "llm-service"
  replicas: 1
  image:
    repository: "ai-tourist-llm-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50054
  metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Geocoding Service
geocodingService:
  name: "geocoding-service"
  replicas: 1
  image:
    repository: "ai-tourist-geocoding-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50055
  metricsPort: 9090
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# POI Service
poiService:
  name: "poi-service"
  replicas: 1
  image:
    repository: "ai-tourist-poi-service"
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 50056
  metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# PostgreSQL
postgresql:
  enabled: true
  port: 5432
  image:
    repository: "postgres"
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  auth:
    username: "aitourist"
    database: "aitourist_db"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Redis
redis:
  enabled: true
  port: 6379
  image:
    repository: "redis"
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Ingress
ingress:
  enabled: true
  className: nginx
