# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\"3\n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tuse_cache\x18\x02 \x01(\x08\"J\n\x11\x45mbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x12\n\nfrom_cache\x18\x02 \x01(\x08\x12\x11\n\tdimension\x18\x03 \x01(\x05\"9\n\x15\x42\x61tchEmbeddingRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x11\n\tuse_cache\x18\x02 \x01(\x08\"E\n\x16\x42\x61tchEmbeddingResponse\x12+\n\x07vectors\x18\x01 \x03(\x0b\x32\x1a.embedding.EmbeddingVector\"5\n\x0f\x45mbeddingVector\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x12\n\nfrom_cache\x18\x02 \x01(\x08\x32\xb9\x01\n\x10\x45mbeddingService\x12N\n\x11GenerateEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\x12U\n\x0e\x42\x61tchEmbedding\x12 .embedding.BatchEmbeddingRequest\x1a!.embedding.BatchEmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=30
  _globals['_EMBEDDINGREQUEST']._serialized_end=81
  _globals['_EMBEDDINGRESPONSE']._serialized_start=83
  _globals['_EMBEDDINGRESPONSE']._serialized_end=157
  _globals['_BATCHEMBEDDINGREQUEST']._serialized_start=159
  _globals['_BATCHEMBEDDINGREQUEST']._serialized_end=216
  _globals['_BATCHEMBEDDINGRESPONSE']._serialized_start=218
  _globals['_BATCHEMBEDDINGRESPONSE']._serialized_end=287
  _globals['_EMBEDDINGVECTOR']._serialized_start=289
  _globals['_EMBEDDINGVECTOR']._serialized_end=342
  _globals['_EMBEDDINGSERVICE']._serialized_start=345
  _globals['_EMBEDDINGSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
